[2022-10-22 15:05:01,985] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T14:05:00+00:00 [queued]>
[2022-10-22 15:05:02,003] {taskinstance.py:1159} INFO - Dependencies all met for <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T14:05:00+00:00 [queued]>
[2022-10-22 15:05:02,004] {taskinstance.py:1356} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 15:05:02,005] {taskinstance.py:1357} INFO - Starting attempt 1 of 2
[2022-10-22 15:05:02,006] {taskinstance.py:1358} INFO - 
--------------------------------------------------------------------------------
[2022-10-22 15:05:02,026] {taskinstance.py:1377} INFO - Executing <Task(ExternalTaskSensor): source_ingest_sensor> on 2022-10-22 14:05:00+00:00
[2022-10-22 15:05:02,033] {standard_task_runner.py:52} INFO - Started process 6806 to run task
[2022-10-22 15:05:02,037] {standard_task_runner.py:79} INFO - Running: ['***', 'tasks', 'run', 'target_ingest_dag', 'source_ingest_sensor', 'scheduled__2022-10-22T14:05:00+00:00', '--job-id', '33', '--raw', '--subdir', 'DAGS_FOLDER/target_ingest_dag.py', '--cfg-path', '/tmp/tmpg_u4xwxw', '--error-file', '/tmp/tmp3pz9v6si']
[2022-10-22 15:05:02,040] {standard_task_runner.py:80} INFO - Job 33: Subtask source_ingest_sensor
[2022-10-22 15:05:02,164] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 15:05:02,184] {task_command.py:369} INFO - Running <TaskInstance: target_ingest_dag.source_ingest_sensor scheduled__2022-10-22T14:05:00+00:00 [running]> on host 865a121acdee
[2022-10-22 15:05:02,236] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/dagrun.py:485 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 15:05:02,312] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/renderedtifields.py:213 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 15:05:02,327] {taskinstance.py:1571} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_EMAIL=rongshiu@gmail.com
AIRFLOW_CTX_DAG_OWNER=rongshiu@gmail.com
AIRFLOW_CTX_DAG_ID=target_ingest_dag
AIRFLOW_CTX_TASK_ID=source_ingest_sensor
AIRFLOW_CTX_EXECUTION_DATE=2022-10-22T14:05:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-22T14:05:00+00:00
[2022-10-22 15:05:02,330] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T14:00:00+00:00 ... 
[2022-10-22 15:05:02,346] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/sensors/external_task.py:230 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 15:06:02,321] {external_task.py:166} INFO - Poking for tasks ['source_ingestion_task'] in dag source_ingest_dag on 2022-10-22T14:00:00+00:00 ... 
[2022-10-22 15:06:02,349] {base.py:301} INFO - Success criteria met. Exiting.
[2022-10-22 15:06:02,375] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=target_ingest_dag, task_id=source_ingest_sensor, execution_date=20221022T140500, start_date=20221022T150501, end_date=20221022T150602
[2022-10-22 15:06:02,415] {local_task_job.py:156} INFO - Task exited with return code 0
[2022-10-22 15:06:02,473] {logging_mixin.py:115} WARNING - /home/***/.local/lib/python3.7/site-packages/***/models/taskinstance.py:2445 SAWarning: TypeDecorator UtcDateTime(timezone=True) will not produce a cache key because the ``cache_ok`` attribute is not set to True.  This can have significant performance implications including some performance degradations in comparison to prior SQLAlchemy versions.  Set this attribute to True if this type object's state is safe to use in a cache key, or False to disable this warning. (Background on this error at: https://sqlalche.me/e/14/cprf)
[2022-10-22 15:06:02,502] {local_task_job.py:273} INFO - 4 downstream tasks scheduled from follow-on schedule check
